export const NOTES_GET_QUERY = 'NOTES_GET_QUERY';

export const NOTES_MUTATION = 'NOTES_MUTATION';

export const NOTES_ADD_MUTATION = 'NOTES_ADD_MUTATION';

export const NOTES_EDIT_MUTATION = 'NOTES_EDIT_MUTATION';

export const NOTES_DELETE_MUTATION = 'NOTES_DELETE_MUTATION';
